# Quadrant Results Table Consolidation

Consolidates regional performance metrics (`SP`, `PF`, `PD` with uncertainties, as percentages $\times 100$) from `quadrant_results.csv` generated by `scripts/run_quadrant_analysis.py` into a standardized LaTeX-formatted grid table (grouped by $E_T$ energy intervals with `SP`, `PF`, and `PD` sub-columns across $|\eta|$ bins, separated by vertical pipes) and exports to CSV.

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import pandas as pd
from src.core.Validation.QuadrantTableConsolidator import QuadrantTableConsolidator

print(f"Project root resolved: {PROJECT_ROOT}")

Project root resolved: /eos/home-i04/p/pmourafr/egamma_master

### 1. Configuration & Strategy Selection

Select the strategy (`strategy1` or `strategy2`), input CSV file, and formatting options (percentage scaling, LaTeX math delimiters, precision, vertical pipes).

In [8]:
# Strategy selection: 'strategy1' or 'strategy2'
STRATEGY = "strategy1"
QUADRANTIC_FOLDER = "ModelV6_50rings_vs_Cut_Loose"

# Input quadrant results CSV path
CSV_PATH = PROJECT_ROOT / f"Plots/quandrantic_analysis/{QUADRANTIC_FOLDER}/quadrant_results.csv"

# Output destination for the formatted CSV
OUTPUT_CSV = PROJECT_ROOT / f"Plots/quandrantic_analysis/{QUADRANTIC_FOLDER}/{STRATEGY}_latex.csv"

# Formatting settings
AS_PERCENTAGE = True     # Multiply values and uncertainties by 100
MATH_DELIMITERS = True   # True: '$val \pm unc$', False: 'val \pm unc'
PRECISION = 2            # Number of decimal places (2 for percentages)
USE_LATEX_LABELS = True  # Use formatted ET and eta LaTeX range descriptions
INCLUDE_GLOBAL = False    # Append composite GLOBAL row at the bottom
INTERVAL_PIPE = True     # Place vertical pipes between ET intervals in LaTeX

print(f"Target strategy: {STRATEGY}")
print(f"Input CSV:        {CSV_PATH}")
print(f"Output CSV:       {OUTPUT_CSV}")
print(f"Percentage mode:  {AS_PERCENTAGE}")
print(f"Interval pipe:    {INTERVAL_PIPE}")

Target strategy: strategy1
Input CSV:        /eos/home-i04/p/pmourafr/egamma_master/Plots/quandrantic_analysis/ModelV6_50rings_vs_Cut_Loose/quadrant_results.csv
Output CSV:       /eos/home-i04/p/pmourafr/egamma_master/Plots/quandrantic_analysis/ModelV6_50rings_vs_Cut_Loose/strategy1_latex.csv
Percentage mode:  True
Interval pipe:    True

### 2. Load Results & Inspect Strategy Name

In [9]:
consolidator = QuadrantTableConsolidator(CSV_PATH)
strategy_name = consolidator.get_strategy_name(STRATEGY)

print(f"Configured Strategy Name: {strategy_name}")
print(f"Total input rows:         {len(consolidator.raw_data)}")

Configured Strategy Name: ModelV6_HighBatch_newExtraction_20_regions_50Rings
Total input rows:         26

### 3. Generate 2D Grid Table ($E_T$ Energy Interval Blocks with SP, PF, PD Sub-Columns)

For each $E_T$ energy interval, the table contains three internal columns: `SP`, `PF`, and `PD` (scaled to percentages). If SP uncertainty is absent, only the metric value is formatted without propagation.

In [10]:
grid_table = consolidator.build_et_grid_table(
    strategy=STRATEGY,
    as_percentage=AS_PERCENTAGE,
    math_delimiters=MATH_DELIMITERS,
    precision=PRECISION,
    use_latex_labels=USE_LATEX_LABELS,
    include_global=INCLUDE_GLOBAL,
)

display(grid_table)

ET Interval              $15 \le E_T < 20\,\text{GeV}$                    \
Metric                                              SP                PF
$|\eta|\text{ Range}$
$0.00 \le |\eta| < 0.80$              $49.21 \pm 1.20$  $80.66 \pm 1.36$
$0.80 \le |\eta| < 1.37$              $55.60 \pm 1.52$  $72.56 \pm 1.99$
$1.37 \le |\eta| < 1.54$              $50.82 \pm 1.31$  $78.59 \pm 1.44$
$1.54 \le |\eta| < 2.37$              $62.68 \pm 0.89$  $62.27 \pm 1.25$
$2.37 \le |\eta| < 2.50$              $42.83 \pm 5.62$  $87.50 \pm 5.23$

ET Interval                                $20 \le E_T < 30\,\text{GeV}$  \
Metric                                  PD                            SP
$|\eta|\text{ Range}$
$0.00 \le |\eta| < 0.80$  $94.15 \pm 0.91$              $74.18 \pm 0.25$
$0.80 \le |\eta| < 1.37$  $94.19 \pm 1.07$              $73.46 \pm 0.33$
$1.37 \le |\eta| < 1.54$  $93.84 \pm 1.66$              $68.99 \pm 0.53$
$1.54 \le |\eta| < 2.37$  $94.13 \pm 0.88$              $74.57 \pm 0.23$
$2.37 \le |\eta| < 2.50$  $94.34 \pm 3.17$              $78.98 \pm 0.70$

ET Interval                                                   \
Metric                                  PF                PD
$|\eta|\text{ Range}$
$0.00 \le |\eta| < 0.80$  $43.45 \pm 0.37$  $94.22 \pm 0.30$
$0.80 \le |\eta| < 1.37$  $44.71 \pm 0.49$  $94.24 \pm 0.37$
$1.37 \le |\eta| < 1.54$  $52.25 \pm 0.76$  $94.18 \pm 0.62$
$1.54 \le |\eta| < 2.37$  $42.79 \pm 0.34$  $94.23 \pm 0.30$
$2.37 \le |\eta| < 2.50$  $34.93 \pm 1.00$  $94.25 \pm 0.96$

ET Interval              $30 \le E_T < 40\,\text{GeV}$                    \
Metric                                              SP                PF
$|\eta|\text{ Range}$
$0.00 \le |\eta| < 0.80$              $86.51 \pm 0.17$  $20.88 \pm 0.26$
$0.80 \le |\eta| < 1.37$              $84.22 \pm 0.22$  $25.24 \pm 0.35$
$1.37 \le |\eta| < 1.54$              $74.37 \pm 0.46$  $43.14 \pm 0.73$
$1.54 \le |\eta| < 2.37$              $84.19 \pm 0.17$  $25.29 \pm 0.26$
$2.37 \le |\eta| < 2.50$              $84.15 \pm 0.48$  $25.33 \pm 0.72$

ET Interval                                $40 \le E_T < 50\,\text{GeV}$  \
Metric                                  PD                            SP
$|\eta|\text{ Range}$
$0.00 \le |\eta| < 0.80$  $94.23 \pm 0.21$              $87.25 \pm 0.19$
$0.80 \le |\eta| < 1.37$  $94.24 \pm 0.25$              $84.43 \pm 0.26$
$1.37 \le |\eta| < 1.54$  $94.24 \pm 0.46$              $75.43 \pm 0.57$
$1.54 \le |\eta| < 2.37$  $94.23 \pm 0.20$              $85.54 \pm 0.19$
$2.37 \le |\eta| < 2.50$  $94.19 \pm 0.62$              $84.17 \pm 0.56$

ET Interval                                                   \
Metric                                  PF                PD
$|\eta|\text{ Range}$
$0.00 \le |\eta| < 0.80$  $19.47 \pm 0.32$  $94.23 \pm 0.20$
$0.80 \le |\eta| < 1.37$  $24.84 \pm 0.44$  $94.24 \pm 0.24$
$1.37 \le |\eta| < 1.54$  $41.26 \pm 0.94$  $94.23 \pm 0.44$
$1.54 \le |\eta| < 2.37$  $22.74 \pm 0.32$  $94.23 \pm 0.20$
$2.37 \le |\eta| < 2.50$  $25.33 \pm 0.93$  $94.24 \pm 0.58$

ET Interval              $E_T \ge 50\,\text{GeV}$                    \
Metric                                         SP                PF
$|\eta|\text{ Range}$
$0.00 \le |\eta| < 0.80$         $78.46 \pm 0.20$  $35.86 \pm 0.35$
$0.80 \le |\eta| < 1.37$         $75.02 \pm 0.27$  $42.00 \pm 0.46$
$1.37 \le |\eta| < 1.54$         $64.30 \pm 0.55$  $59.83 \pm 0.84$
$1.54 \le |\eta| < 2.37$         $73.61 \pm 0.21$  $44.45 \pm 0.36$
$2.37 \le |\eta| < 2.50$         $71.75 \pm 0.60$  $47.65 \pm 0.99$

ET Interval
Metric                                  PD
$|\eta|\text{ Range}$
$0.00 \le |\eta| < 0.80$  $94.24 \pm 0.10$
$0.80 \le |\eta| < 1.37$  $94.24 \pm 0.11$
$1.37 \le |\eta| < 1.54$  $94.23 \pm 0.22$
$1.54 \le |\eta| < 2.37$  $94.24 \pm 0.09$
$2.37 \le |\eta| < 2.50$  $94.23 \pm 0.28$

### 4. Inspect Numeric Metrics (Optional Reference)

Raw numeric values and uncertainties (scaled to percentages) preserved as floating-point numbers.

In [11]:
numeric_table = consolidator.build_numeric_table(
    strategy=STRATEGY,
    as_percentage=AS_PERCENTAGE,
    include_global=INCLUDE_GLOBAL,
)

display(numeric_table.head(10))

,region,iet,ieta,sp,sp_uncertainty,pd,pd_uncertainty,pf,pf_uncertainty
0,iet0.ieta0,0,0,49.208386,1.199084,94.152924,0.908497,80.660377,1.356301
1,iet0.ieta1,0,1,55.600495,1.516598,94.190871,1.065458,72.564612,1.989454
2,iet0.ieta2,0,2,50.822892,1.314007,93.838863,1.655315,78.589109,1.443088
3,iet0.ieta3,0,3,62.683674,0.893189,94.125874,0.879373,62.265416,1.254899
4,iet0.ieta4,0,4,42.830408,5.616560,94.339623,3.174182,87.500000,5.229125
5,iet1.ieta0,1,0,74.182573,0.253706,94.224255,0.303607,43.448670,0.374867
6,iet1.ieta1,1,1,73.462020,0.325354,94.241362,0.368618,44.713020,0.487917
7,iet1.ieta2,1,2,68.985082,0.529949,94.180270,0.623700,52.250173,0.758814
8,iet1.ieta3,1,3,74.565722,0.233746,94.231734,0.301463,42.785750,0.335015
9,iet1.ieta4,1,4,78.983345,0.703606,94.247039,0.957824,34.927600,0.998644

### 5. Export Formatted Table to CSV

In [12]:
saved_path = consolidator.export_csv(grid_table, OUTPUT_CSV)
print(f"Consolidated grid table exported successfully to: {saved_path}")

Consolidated grid table exported successfully to: /eos/home-i04/p/pmourafr/egamma_master/Plots/quandrantic_analysis/ModelV6_50rings_vs_Cut_Loose/strategy1_latex.csv

### 6. LaTeX Code Generation

Ready-to-use LaTeX tabular snippet with multicolumn blocks for each $E_T$ energy interval separated by vertical pipes, wrapped with `\resizebox{\textwidth}{!}{...}` to ensure proper document margin fit.

In [13]:
caption = f"Regional performance metrics (SP, PF, PD in \\%) for {strategy_name} across $E_T$ and $|\\eta|$ intervals"
label = f"tab:regional_efficiencies_{STRATEGY}"

latex_snippet = consolidator.to_latex_snippet(
    grid_table,
    caption=caption,
    label=label,
    resize_box=True,
    interval_pipe=INTERVAL_PIPE,
)

print(latex_snippet)

\begin{table}[htbp]
\centering
\caption{Regional performance metrics (SP, PF, PD in \%) for ModelV6_HighBatch_newExtraction_20_regions_50Rings across $E_T$ and $|\eta|$ intervals}
\label{tab:regional_efficiencies_strategy1}
\resizebox{\textwidth}{!}{%
\begin{tabular}{l | ccc | ccc | ccc | ccc | ccc}
\toprule
ET Interval & \multicolumn{3}{c|}{$15 \le E_T < 20\,\text{GeV}$} & \multicolumn{3}{c|}{$20 \le E_T < 30\,\text{GeV}$} & \multicolumn{3}{c|}{$30 \le E_T < 40\,\text{GeV}$} & \multicolumn{3}{c|}{$40 \le E_T < 50\,\text{GeV}$} & \multicolumn{3}{c}{$E_T \ge 50\,\text{GeV}$} \\
Metric & SP & PF & PD & SP & PF & PD & SP & PF & PD & SP & PF & PD & SP & PF & PD \\
$|\eta|\text{ Range}$ &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
\midrule
$0.00 \le |\eta| < 0.80$ & $49.21 \pm 1.20$ & $80.66 \pm 1.36$ & $94.15 \pm 0.91$ & $74.18 \pm 0.25$ & $43.45 \pm 0.37$ & $94.22 \pm 0.30$ & $86.51 \pm 0.17$ & $20.88 \pm 0.26$ & $94.23 \pm 0.21$ & $87.25 \pm 0.19$ & $19.47 \pm 0.32$ & $94.23 \pm 0.20$ & $78.46 \pm 0.20$ & $35.86 \pm 0.35$ & $94.24 \pm 0.10$ \\
$0.80 \le |\eta| < 1.37$ & $55.60 \pm 1.52$ & $72.56 \pm 1.99$ & $94.19 \pm 1.07$ & $73.46 \pm 0.33$ & $44.71 \pm 0.49$ & $94.24 \pm 0.37$ & $84.22 \pm 0.22$ & $25.24 \pm 0.35$ & $94.24 \pm 0.25$ & $84.43 \pm 0.26$ & $24.84 \pm 0.44$ & $94.24 \pm 0.24$ & $75.02 \pm 0.27$ & $42.00 \pm 0.46$ & $94.24 \pm 0.11$ \\
$1.37 \le |\eta| < 1.54$ & $50.82 \pm 1.31$ & $78.59 \pm 1.44$ & $93.84 \pm 1.66$ & $68.99 \pm 0.53$ & $52.25 \pm 0.76$ & $94.18 \pm 0.62$ & $74.37 \pm 0.46$ & $43.14 \pm 0.73$ & $94.24 \pm 0.46$ & $75.43 \pm 0.57$ & $41.26 \pm 0.94$ & $94.23 \pm 0.44$ & $64.30 \pm 0.55$ & $59.83 \pm 0.84$ & $94.23 \pm 0.22$ \\
$1.54 \le |\eta| < 2.37$ & $62.68 \pm 0.89$ & $62.27 \pm 1.25$ & $94.13 \pm 0.88$ & $74.57 \pm 0.23$ & $42.79 \pm 0.34$ & $94.23 \pm 0.30$ & $84.19 \pm 0.17$ & $25.29 \pm 0.26$ & $94.23 \pm 0.20$ & $85.54 \pm 0.19$ & $22.74 \pm 0.32$ & $94.23 \pm 0.20$ & $73.61 \pm 0.21$ & $44.45 \pm 0.36$ & $94.24 \pm 0.09$ \\
$2.37 \le |\eta| < 2.50$ & $42.83 \pm 5.62$ & $87.50 \pm 5.23$ & $94.34 \pm 3.17$ & $78.98 \pm 0.70$ & $34.93 \pm 1.00$ & $94.25 \pm 0.96$ & $84.15 \pm 0.48$ & $25.33 \pm 0.72$ & $94.19 \pm 0.62$ & $84.17 \pm 0.56$ & $25.33 \pm 0.93$ & $94.24 \pm 0.58$ & $71.75 \pm 0.60$ & $47.65 \pm 0.99$ & $94.23 \pm 0.28$ \\
\bottomrule
\end{tabular}
}
\end{table}